# Generated by Django 4.1.13 on 2024-07-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='questions_answers',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
