# Generated by Django 4.1.13 on 2024-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_questions_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='question_10_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_1_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_2_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_3_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_4_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_5_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_7_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_8_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_9_sentiment',
            field=models.CharField(default='Not analyzed', max_length=20),
        ),
    ]
