# Generated by Django 5.0.4 on 2024-07-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_question_10_sentiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question_10',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_10_sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_6',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_6_sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_7',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_7_sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_8',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_8_sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_9',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question_9_sentiment',
        ),
    ]
