# Generated by Django 4.1.13 on 2024-07-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_emotion'),
    ]

    operations = [
    ]
