# Generated by Django 5.0.4 on 2024-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_chatemotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatemotion',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='chatemotion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
